# Generated by Django 6.0.7 on 2026-07-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_created_at_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.RunSQL("UPDATE users_user SET deleted_at = NULL;"),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
